calibration_detector:
  preprocessing:
    block_radius: 50
    c: 20
  pattern:
    path: img/calibration_320.png
    scale: 0.25
    color: False
  detector:
    match_threshold: 0.5
    clustering_bandwidth: 40